### ISSUE TITLE
lcd.tx.txInfo not working for specific transactions

### ISSUE THREAD

**Issue by jer-lim** [terra-money/terra.js#164]
terra.js version: v2.0.15

Example failing tx, unsure of what is the cause:

`lcd.tx.txInfo("F9EB9352EC1279FE8E982379DD3D641890430FFE6A6149B9A0D2ECC9ECF14D57")`

Stack trace:

```
Error: unable to parse msg: [object Object] unrecognized
    at Object.fromData (redacted\node_modules\@terra-money\terra.js\dist\core\Msg.js:87:15)
    at redacted\node_modules\@terra-money\terra.js\dist\core\StdTx.js:49:66
    at Array.map (<anonymous>)
    at Function.StdTx.fromData (redacted\node_modules\@terra-money\terra.js\dist\core\StdTx.js:49:30)
    at TxInfo.fromData (redacted\node_modules\@terra-money\terra.js\dist\core\TxInfo.js:54:240)
```

**Comment by Vritra4** [comment]
sorry for the late response. you need to use terra.js 3.x.
