### ISSUE TITLE
Staking API test fails consistently

### ISSUE THREAD

**Issue by decryptdavid** [terra-money/terra.js#166]
The Staking API test seems to fail now, consistently, possibly since it's hitting real test data and that data has changed.

```
 FAIL  src/client/lcd/api/StakingAPI.spec.ts (12.448 s)
  ● StakingAPI › delegations (delegator)

    expect(received).resolves.toContainEqual(expected) // deep equality

    Expected value: {"balance": Any<Coin>, "delegator_address": Any<String>, "shares": Any<Dec>, "validator_address": Any<String>}
    Received array: []

      21 |     await expect(
      22 |       staking.delegations('terra1940nsxkz62snd3azk3a9j79m4qd3qvwnrf2xvj')
    > 23 |     ).resolves.toContainEqual({
         |                ^
      24 |       delegator_address: expect.any(String),
      25 |       validator_address: expect.any(String),
      26 |       shares: expect.any(Dec),

      at Object.toContainEqual (node_modules/expect/build/index.js:242:22)
      at src/client/lcd/api/StakingAPI.spec.ts:23:16
      at step (src/client/lcd/api/StakingAPI.spec.ts:33:23)
      at Object.next (src/client/lcd/api/StakingAPI.spec.ts:14:53)
      at src/client/lcd/api/StakingAPI.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/client/lcd/api/StakingAPI.spec.ts:4:12)
      at Object.<anonymous> (src/client/lcd/api/StakingAPI.spec.ts:20:33)

Summary of all failing tests
 FAIL  src/client/lcd/api/StakingAPI.spec.ts (12.448 s)
  ● StakingAPI › delegations (delegator)

    expect(received).resolves.toContainEqual(expected) // deep equality

    Expected value: {"balance": Any<Coin>, "delegator_address": Any<String>, "shares": Any<Dec>, "validator_address": Any<String>}
    Received array: []

      21 |     await expect(
      22 |       staking.delegations('terra1940nsxkz62snd3azk3a9j79m4qd3qvwnrf2xvj')
    > 23 |     ).resolves.toContainEqual({
         |                ^
      24 |       delegator_address: expect.any(String),
      25 |       validator_address: expect.any(String),
      26 |       shares: expect.any(Dec),

      at Object.toContainEqual (node_modules/expect/build/index.js:242:22)
      at src/client/lcd/api/StakingAPI.spec.ts:23:16
      at step (src/client/lcd/api/StakingAPI.spec.ts:33:23)
      at Object.next (src/client/lcd/api/StakingAPI.spec.ts:14:53)
      at src/client/lcd/api/StakingAPI.spec.ts:8:71
      at Object.<anonymous>.__awaiter (src/client/lcd/api/StakingAPI.spec.ts:4:12)
      at Object.<anonymous> (src/client/lcd/api/StakingAPI.spec.ts:20:33)


Test Suites: 1 failed, 57 passed, 58 total
Tests:       1 failed, 111 passed, 112 total
Snapshots:   0 total
Time:        13.291 s
Ran all test suites.
```

**Comment by auracheeze** [comment]
It appears to be a change in the API behaviour related to the upgrade.

**Comment by hanjukim** [comment]
This is a known issue that API tests requires the actual testnet access to test the actual state, and some of StakingAPI test requires specific address for checking unbonding and redelegation queries.

We could create a mock module for removing the hard dependency, but since CosmosSDK is always making breaking changes, we didn't do it.
