### ISSUE TITLE
m.packAny is not a function   (terra.js@3.0.0

### ISSUE THREAD

**Issue by ivanfong01** [terra-money/terra.js#179]
"type": "TypeError",
      "message": "m.packAny is not a function",
      "stack":
          TypeError: m.packAny is not a function
              at \@terra-money\terra.js\dist\core\Tx.js:125:65
              at Array.map (<anonymous>)
              at TxBody.toProto (\@terra-money\terra.js\dist\core\Tx.js:125:37)
              at Tx.toProto (\@terra-money\terra.js\dist\core\Tx.js:59:29)
              at Tx.toBytes (\@terra-money\terra.js\dist\core\Tx.js:65:36)
              at TxAPI.encode (\@terra-money\terra.js\dist\client\lcd\api\TxAPI.js:273:31)
              at TxAPI.<anonymous> (\@terra-money\terra.js\dist\client\lcd\api\TxAPI.js:241:48)
              at step (\@terra-money\terra.js\dist\client\lcd\api\TxAPI.js:48:23)
              at Object.next (\@terra-money\terra.js\dist\client\lcd\api\TxAPI.js:29:53)
              at \@terra-money\terra.js\dist\client\lcd\api\TxAPI.js:23:71

**Comment by ivanfong01** [comment]
it happens when using MsgSend, but it works fine with MsgExecuteContract

It even fails with createAndSignTx

**Comment by Vritra4** [comment]
would you reinstall terra.js? MsgSend works for me.
