### ISSUE TITLE
Creating MnemonicKey causes TypeError on terra.js

### ISSUE THREAD

**Issue by SpaceyCodes** [terra-money/terra.js#234]
I am currently trying to create a React App with terra.js. When I ran the code below, encountered a TypeError saying that the property was undefined.
```
const mk = new MnemonicKey({
        mnemonic:
            'notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius',
    });
console.log(mk)
```
Full error:
```
index.js:7 Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Hash.CipherBase (index.js:7:1)
    at new Hash (browser.js:9:1)
    at createHash (browser.js:29:1)
    at deriveChecksumBits (index.js:44:1)
    at entropyToMnemonic (index.js:127:1)
    at Object.generateMnemonic (index.js:145:1)
    at new MnemonicKey (MnemonicKey.ts:77:1)
    at CryptoInit (CryptoInit.js:10:1)
    at App (App.js:5:1)
    at renderWithHooks (react-dom.development.js:14985:1)
```
I know that it should not be a problem with my import as I am able to console.log my LCDClient. So I was wondering what I am doing wrongly.

**Comment by SpaceyCodes** [comment]
Sorry. I figured out the problem. The problem was due to myself. I installed "stream" instead of "stream-browserify". After installing the right package, the code works.
