### ISSUE TITLE
TxAPI.txInfosByHeight failed to fetch transactions for block 6684800

### ISSUE THREAD

**Issue by anthony-zhan** [terra-money/terra.js#240]
It's weird that `TxAPI.txInfosByHeight` throws the error below for looking up transactions but only for block `6684800`, (other blocks are fine).
```
Error: cannot set both of spend_limit and expiration empty
    at new BasicAllowance (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/feegrant/allowances/BasicAllowance.ts:33:13)
    at Function.BasicAllowance.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/feegrant/allowances/BasicAllowance.ts:64:12)
    at Object.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/feegrant/allowances/index.ts:47:31)
    at Function.MsgGrantAllowance.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/feegrant/msgs/MsgGrantAllowance.ts:58:17)
    at Object.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/Msg.ts:258:34)
    at /Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/Tx.ts:176:34
    at Array.map (<anonymous>)
    at Function.TxBody.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/Tx.ts:176:21)
    at Function.Tx.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/Tx.ts:51:14)
    at Function.TxInfo.fromData (/Users/xxxx/space/projects/xxx/node_modules/@terra-money/terra.js/src/core/TxInfo.ts:61:10)
```

Here is the example code
```ts
  const terra = new LCDClient({
    URL: 'https://lcd.terra.dev',
    chainID: 'columbus-3',
  });
  const txInfos = await terra.tx.txInfosByHeight(6684800);
  console.log(txInfos);
```

**Comment by anhcao142** [comment]
Hi, I'm also getting this, can you publish a fix sooner?
