### ISSUE TITLE
Cannot get pool for CW20 from LCDClient Query

### ISSUE THREAD

**Issue by tori-9** [terra-money/terra.js#268]
I ran this query in node CLI for Swapping CW20 Token And LUNA
```
client = new terra.LCDClient({ URL : "https://bombay-lcd.terra.dev", chainID : "bombay-12", gasPrices : { uluna : 0.01133 }})
ANC = "terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc"
{ anc_asset } = await client.wasm.contractQuery( ANC, { pool : {} })
```
But I got this messages
```
Uncaught Error: Request failed with status code 500
    at createError (/Users/tori/dev/mainmeta/rnd/terra/test/tori_api/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/tori/dev/mainmeta/rnd/terra/test/tori_api/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/tori/dev/mainmeta/rnd/terra/test/tori_api/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:538:35)
    at IncomingMessage.emit (node:domain:537:15)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 30000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: { Accept: 'application/json', 'User-Agent': 'axios/0.26.1' },
    baseURL: 'https://bombay-lcd.terra.dev',
    params: { query_msg: 'eyJwb29sIjp7fX0=' },
    method: 'get',
    url: '/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store',
    data: undefined
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'bombay-lcd.terra.dev',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'bombay-lcd.terra.dev',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 30000,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 1605,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 30000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 127969,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 1626,
        [Symbol(triggerId)]: 1609
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'GET /terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D HTTP/1.1\r\n' +
      'Accept: application/json\r\n' +
      'User-Agent: axios/0.26.1\r\n' +
      'Host: bombay-lcd.terra.dev\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 500,
      statusMessage: 'Internal Server Error',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://bombay-lcd.terra.dev/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 30,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'bombay-lcd.terra.dev',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://bombay-lcd.terra.dev/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 500,
    statusText: 'Internal Server Error',
    headers: {
      date: 'Fri, 29 Apr 2022 03:03:42 GMT',
      'content-type': 'application/json',
      'content-length': '298',
      connection: 'close',
      'x-server-time': '1651201422',
      'access-control-allow-origin': '*',
      'access-control-allow-methods': 'GET, POST, OPTIONS',
      'access-control-allow-headers': 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range',
      'access-control-expose-headers': 'Content-Length,Content-Range',
      'cf-cache-status': 'DYNAMIC',
      'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
      'set-cookie': [Array],
      server: 'cloudflare',
      'cf-ray': '7034ce5d5836a7b9-ICN',
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 30000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      baseURL: 'https://bombay-lcd.terra.dev',
      params: [Object],
      method: 'get',
      url: '/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store',
      data: undefined
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D HTTP/1.1\r\n' +
        'Accept: application/json\r\n' +
        'User-Agent: axios/0.26.1\r\n' +
        'Host: bombay-lcd.terra.dev\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/terra/wasm/v1beta1/contracts/terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc/store?query_msg=eyJwb29sIjp7fX0%3D',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'bombay-lcd.terra.dev',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: {
      code: 2,
      message: 'rpc error: code = Internal desc = Error parsing into type cw20_legacy::msg::QueryMsg: unknown variant `pool`, expected one of `balance`, `token_info`, `minter`, `allowance`, `all_allowances`, `all_accounts`: contract query failed: unknown request',
      details: []
    }
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

Why did I get this message ? 
I just follow up [This Sample - Swapping a native Terra asset for a CW20 token using Terraswap](https://docs.terra.money/docs/develop/sdks/terra-js/common-examples.html#swapping-a-native-terra-asset-for-a-cw20-token-using-terraswap)

**Comment by Vritra4** [comment]
terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc is not a terraswap contract.

**Comment by tori-9** [comment]
terra1747mad58h0w4y589y3sk84r5efqdev9q4r02pc is Contract of Anchor Protocol (ANC) on Bombay Testnet
The Contract Address is published on docs.terra.dev - Example of "Get Wallet Balance (CW20 Tokens) - ANC Bombay"

**Comment by Vritra4** [comment]
yes terra...02pc is ANC token contract. not a swap contract. that's why `{pool:{}}` failed.
and it's not about terra.js. you should ask about it to terraswap guys.

**Comment by tori-9** [comment]
@Vritra4 OK I understood. 
But I ran below query on [Swapping a native Terra asset for a CW20 token using Terraswap](https://docs.terra.money/docs/develop/sdks/terra-js/common-examples.html#swapping-a-native-terra-asset-for-a-cw20-token-using-terraswap)
```
// UST <> SCRT
const pool = "terra1tq4mammgkqrxrmcfhwdz59mwvwf4qgy6rdrt46";
// Fetch the number of each asset in the pool.
const { assets } = await lcd.wasm.contractQuery(pool, { pool: {} });
```
It took same error

**Comment by Vritra4** [comment]
@tori-9 did you query terra1tq4mammgkqrxrmcfhwdz59mwvwf4qgy6rdrt46 on testnet? terra1tq4mammgkqrxrmcfhwdz59mwvwf4qgy6rdrt46 lives on mainnet only.
if you did it do mainnet, could you share part of your source? (be aware of privacy). because i did same on mainnet and it works.

**Comment by tori-9** [comment]
Yes I queried on testnet. 
I queried Mainnet and I can get Data. Sorry for confusing
