### ISSUE TITLE
TypeError: m.packAny is not a function

### ISSUE THREAD

**Issue by Addis-Belete** [terra-money/terra.js#270]
I am getting the below error while trying to create and sign a transaction. I need help.
```
transaction failed due to:- TypeError: m.packAny is not a function
    at /Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/core/Tx.ts:201:42
    at Array.map (<anonymous>)
    at TxBody.toProto (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/core/Tx.ts:201:31)
    at Tx.toProto (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/core/Tx.ts:79:23)
    at Tx.toBytes (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/core/Tx.ts:86:30)
    at TxAPI.encode (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/client/lcd/api/TxAPI.ts:358:27)
    at TxAPI.<anonymous> (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/src/client/lcd/api/TxAPI.ts:342:24)
    at step (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/dist/client/lcd/api/TxAPI.js:48:23)
    at Object.next (/Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/dist/client/lcd/api/TxAPI.js:29:53)
    at /Users/beki/cryptup/kryptup-blockchain/node_modules/@terra-money/terra.js/dist/client/lcd/api/TxAPI.js:23:71
```

**Comment by Vritra4** [comment]
could you show me the tx you made?

**Comment by Addis-Belete** [comment]
Thanks! fixed
