### ISSUE TITLE
TypeError: m.packAny is not a function in nodejs

### ISSUE THREAD

**Issue by joradn222** [terra-money/terra.js#307]
I am running this code on pisco testnet:
```
const signedTx = await this.wallet.createAndSignTx({
      msgs: [some_msg],
      gasPrices: "0.15uluna",
      fee: new Fee(500000, { uluna: "500000" }),
    });
```

and its throwing this error
```
TypeError: m.packAny is not a function
    at /home/a/project/node_modules/@terra-money/terra.js/dist/core/Tx.js:132:65
```

I am using terra.js: `3.1.3`.

**Comment by Vritra4** [comment]
what kind of `some_msg` is it?

**Comment by joradn222** [comment]
```
let msg = {
      swap: {
        belief_price: "650",
        max_spread: "1000",
        offer_asset: {
          info: { native_token: { denom: "uluna" } },
          amount: "100000",
        },
      },
    };
```

**Comment by joradn222** [comment]
Here is the full error log:
```
/home/abc/def/node_modules/@terra-money/terra.js/dist/core/Tx.js:132
            messages: this.messages.map(function (m) { return m.packAny(isClassic); }),
                                                                ^

TypeError: m.packAny is not a function
    at /home/abc/def/node_modules/@terra-money/terra.js/dist/core/Tx.js:132:65
    at Array.map (<anonymous>)
    at TxBody.toProto (/home/abc/def/node_modules/@terra-money/terra.js/dist/core/Tx.js:132:37)
    at TxBody.toBytes (/home/abc/def/node_modules/@terra-money/terra.js/dist/core/Tx.js:137:40)
    at SignDoc.toProto (/home/abc/def/node_modules/@terra-money/terra.js/dist/core/SignDoc.js:101:32)
    at SignDoc.toBytes (/home/abc/def/node_modules/@terra-money/terra.js/dist/core/SignDoc.js:111:41)
    at MnemonicKey.<anonymous> (/home/abc/def/node_modules/@terra-money/terra.js/dist/key/Key.js:143:76)
    at step (/home/abc/def/node_modules/@terra-money/terra.js/dist/key/Key.js:33:23)
    at Object.next (/home/abc/def/node_modules/@terra-money/terra.js/dist/key/Key.js:14:53)
    at /home/abc/def/node_modules/@terra-money/terra.js/dist/key/Key.js:8:71
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Vritra4** [comment]
closing due to inactivity. please feel free to reopen it if you are still having a problem.
